"""add_scrum_daily_weekly_log

Revision ID: 3ec46886c25e
Revises: 020_add_prd_to_document_type_enum
Create Date: 2026-09-30 12:46:35.004105

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ec46886c25e'
down_revision: Union[str, None] = '020_add_prd_to_document_type_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrum_sessions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_year', sa.Integer(), nullable=False),
    sa.Column('facilitator_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facilitator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'session_date', name='uq_scrum_session_project_date')
    )
    op.create_index(op.f('ix_scrum_sessions_facilitator_id'), 'scrum_sessions', ['facilitator_id'], unique=False)
    op.create_index(op.f('ix_scrum_sessions_id'), 'scrum_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_scrum_sessions_session_date'), 'scrum_sessions', ['session_date'], unique=False)
    op.create_table('scrum_weekly_reports',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_year', sa.Integer(), nullable=False),
    sa.Column('generated_by_id', sa.Uuid(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('report_markdown', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'week_year', 'week_number', name='uq_scrum_report_project_week')
    )
    op.create_index(op.f('ix_scrum_weekly_reports_id'), 'scrum_weekly_reports', ['id'], unique=False)
    op.create_index(op.f('ix_scrum_weekly_reports_project_id'), 'scrum_weekly_reports', ['project_id'], unique=False)
    op.create_table('scrum_entries',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('member_name', sa.String(length=255), nullable=False),
    sa.Column('what_done', sa.Text(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('what_next', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['project_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['scrum_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrum_entries_id'), 'scrum_entries', ['id'], unique=False)
    op.create_index(op.f('ix_scrum_entries_member_id'), 'scrum_entries', ['member_id'], unique=False)
    op.create_index(op.f('ix_scrum_entries_project_id'), 'scrum_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_scrum_entries_session_id'), 'scrum_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_action_items_id'), 'action_items', ['id'], unique=False)
    op.create_index(op.f('ix_activity_events_id'), 'activity_events', ['id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_id'), 'ai_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_suggestions_id'), 'ai_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_blockers_id'), 'blockers', ['id'], unique=False)
    op.create_index(op.f('ix_briefs_id'), 'briefs', ['id'], unique=False)
    op.create_index(op.f('ix_client_answers_id'), 'client_answers', ['id'], unique=False)
    op.create_index(op.f('ix_client_dependencies_id'), 'client_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_discovery_questions_id'), 'discovery_questions', ['id'], unique=False)
    op.create_index(op.f('ix_document_evidences_id'), 'document_evidences', ['id'], unique=False)
    op.create_index(op.f('ix_epics_id'), 'epics', ['id'], unique=False)
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    op.create_index(op.f('ix_generated_documents_id'), 'generated_documents', ['id'], unique=False)
    op.create_index(op.f('ix_handover_items_id'), 'handover_items', ['id'], unique=False)
    op.create_index(op.f('ix_handovers_id'), 'handovers', ['id'], unique=False)
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_id'), 'meeting_participants', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.alter_column('mom_documents', 'attendees',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('mom_documents', 'action_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('mom_documents', 'decisions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_report_evidences_id'), 'report_evidences', ['id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_requirements_id'), 'requirements', ['id'], unique=False)
    op.create_index(op.f('ix_risks_id'), 'risks', ['id'], unique=False)
    op.create_index(op.f('ix_risks_materialized_issue_id'), 'risks', ['materialized_issue_id'], unique=False)
    op.create_foreign_key(None, 'risks', 'issues', ['materialized_issue_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_scope_changes_id'), 'scope_changes', ['id'], unique=False)
    op.create_index(op.f('ix_scope_items_id'), 'scope_items', ['id'], unique=False)
    op.create_index(op.f('ix_stakeholders_id'), 'stakeholders', ['id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_id'), 'task_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_task_dependencies_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_stakeholders_id'), table_name='stakeholders')
    op.drop_index(op.f('ix_scope_items_id'), table_name='scope_items')
    op.drop_index(op.f('ix_scope_changes_id'), table_name='scope_changes')
    op.drop_constraint(None, 'risks', type_='foreignkey')
    op.drop_index(op.f('ix_risks_materialized_issue_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_id'), table_name='risks')
    op.drop_index(op.f('ix_requirements_id'), table_name='requirements')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_report_evidences_id'), table_name='report_evidences')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.alter_column('mom_documents', 'decisions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('mom_documents', 'action_items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('mom_documents', 'attendees',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_index(op.f('ix_meeting_participants_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_index(op.f('ix_handovers_id'), table_name='handovers')
    op.drop_index(op.f('ix_handover_items_id'), table_name='handover_items')
    op.drop_index(op.f('ix_generated_documents_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_index(op.f('ix_epics_id'), table_name='epics')
    op.drop_index(op.f('ix_document_evidences_id'), table_name='document_evidences')
    op.drop_index(op.f('ix_discovery_questions_id'), table_name='discovery_questions')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_client_dependencies_id'), table_name='client_dependencies')
    op.drop_index(op.f('ix_client_answers_id'), table_name='client_answers')
    op.drop_index(op.f('ix_briefs_id'), table_name='briefs')
    op.drop_index(op.f('ix_blockers_id'), table_name='blockers')
    op.drop_index(op.f('ix_ai_suggestions_id'), table_name='ai_suggestions')
    op.drop_index(op.f('ix_ai_jobs_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_activity_events_id'), table_name='activity_events')
    op.drop_index(op.f('ix_action_items_id'), table_name='action_items')
    op.drop_index(op.f('ix_scrum_entries_session_id'), table_name='scrum_entries')
    op.drop_index(op.f('ix_scrum_entries_project_id'), table_name='scrum_entries')
    op.drop_index(op.f('ix_scrum_entries_member_id'), table_name='scrum_entries')
    op.drop_index(op.f('ix_scrum_entries_id'), table_name='scrum_entries')
    op.drop_table('scrum_entries')
    op.drop_index(op.f('ix_scrum_weekly_reports_project_id'), table_name='scrum_weekly_reports')
    op.drop_index(op.f('ix_scrum_weekly_reports_id'), table_name='scrum_weekly_reports')
    op.drop_table('scrum_weekly_reports')
    op.drop_index(op.f('ix_scrum_sessions_session_date'), table_name='scrum_sessions')
    op.drop_index(op.f('ix_scrum_sessions_id'), table_name='scrum_sessions')
    op.drop_index(op.f('ix_scrum_sessions_facilitator_id'), table_name='scrum_sessions')
    op.drop_table('scrum_sessions')
    # ### end Alembic commands ###
