"""add_scrum_daily_weekly_log

Revision ID: 3ec46886c25e
Revises: 020_add_prd_to_document_type_enum
Create Date: 2026-09-30 12:46:35.004105

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ec46886c25e'
down_revision: Union[str, None] = '020_add_prd_to_document_type_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrum_sessions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_year', sa.Integer(), nullable=False),
    sa.Column('facilitator_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facilitator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'session_date', name='uq_scrum_session_project_date')
    )
    op.create_index(op.f('ix_scrum_sessions_facilitator_id'), 'scrum_sessions', ['facilitator_id'], unique=False)
    op.create_index(op.f('ix_scrum_sessions_id'), 'scrum_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_scrum_sessions_session_date'), 'scrum_sessions', ['session_date'], unique=False)
    op.create_table('scrum_weekly_reports',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_year', sa.Integer(), nullable=False),
    sa.Column('generated_by_id', sa.Uuid(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('report_markdown', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'week_year', 'week_number', name='uq_scrum_report_project_week')
    )
    op.create_index(op.f('ix_scrum_weekly_reports_id'), 'scrum_weekly_reports', ['id'], unique=False)
    op.create_index(op.f('ix_scrum_weekly_reports_project_id'), 'scrum_weekly_reports', ['project_id'], unique=False)
    op.create_table('scrum_entries',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('member_name', sa.String(length=255), nullable=False),
    sa.Column('what_done', sa.Text(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('what_next', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['project_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['scrum_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrum_entries_id'), 'scrum_entries', ['id'], unique=False)
    op.create_index(op.f('ix_scrum_entries_member_id'), 'scrum_entries', ['member_id'], unique=False)
    op.create_index(op.f('ix_scrum_entries_project_id'), 'scrum_entries', ['project_id'], unique=False)
    op.create_index(op.f('ix_scrum_entries_session_id'), 'scrum_entries', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrum_entries_session_id'), table_name='scrum_entries')
    op.drop_index(op.f('ix_scrum_entries_project_id'), table_name='scrum_entries')
    op.drop_index(op.f('ix_scrum_entries_member_id'), table_name='scrum_entries')
    op.drop_index(op.f('ix_scrum_entries_id'), table_name='scrum_entries')
    op.drop_table('scrum_entries')
    op.drop_index(op.f('ix_scrum_weekly_reports_project_id'), table_name='scrum_weekly_reports')
    op.drop_index(op.f('ix_scrum_weekly_reports_id'), table_name='scrum_weekly_reports')
    op.drop_table('scrum_weekly_reports')
    op.drop_index(op.f('ix_scrum_sessions_session_date'), table_name='scrum_sessions')
    op.drop_index(op.f('ix_scrum_sessions_id'), table_name='scrum_sessions')
    op.drop_index(op.f('ix_scrum_sessions_facilitator_id'), table_name='scrum_sessions')
    op.drop_table('scrum_sessions')
    # ### end Alembic commands ###
